#124 - Project Details Block Pattern
WordPress/twentytwentyfour pull request #189
Opened 2023-09-04 15:12 UTC by khleomix

**Description**
- #124 Create Project Details Block Pattern

**Screenshots**

![image](https://github.com/WordPress/twentytwentyfour/assets/1948204/4f72afc7-85a2-4e53-8c28-6a1725c495f8)

**Testing Instructions**
1. Create/Edit a page.
2. Add a pattern -> text -> Project Details
3. Edit where necessary

**Contributors**
khleomix

2023-09-04 16:04 UTC, MaggieCabrera commented
The markup for this pattern was already provided by Bea but since it wasn't on a template I didn't include it in the original PR. Can you please check your markup against hers [here](https://github.com/WordPress/twentytwentyfour/issues/188) to check that it all aligns?

2023-09-04 17:45 UTC, khleomix commented
@MaggieCabrera I've updated the pattern to the provided markup. Let me know if that works.

2023-09-05 06:37 UTC, maneshtimilsina requested changes
Here are a few of my quick findings. 

- Please use the spacing presets instead of arbitrary values for paddings where needed.
- Use `esc_html_x` with context instead of `esc_html`. You can check `404.php` or other approved patterns for the reference.

2023-09-05 20:23 UTC, MaggieCabrera commented on patterns/project-details.php
> +<div class="wp-block-group alignfull has-base-background-color has-background" style="padding-top:8vh;padding-right:6vw;padding-bottom:8vh;padding-left:6vw"><!-- wp:columns {"align":"wide","style":{"
can we use presets instead here for the padding?

2023-09-05 20:24 UTC, MaggieCabrera commented on patterns/project-details.php
> +<div class="wp-block-column" style="flex-basis:15%"><!-- wp:paragraph {"style":{"typography":{"fontSize":"0.8rem","lineHeight":"1.4"}}} -->
same about font size presets here

2023-09-06 09:59 UTC, MaggieCabrera approved these changes
I changed the spacing values, let's bring this in and iterate

2023-09-06 10:00 UTC, merged