Centered Statement pattern
WordPress/twentytwentyfour pull request #48
Opened 2023-08-24 19:33 UTC by amedv

Centered Statement pattern based on Figma template. Set to wide width and with paddings on all sides and text centered. Text translation split into three strings because of use <em> tag for name highlight. Original text in Figma written in Italian, used Google Translate to translate into English.

2023-09-02 06:10 UTC, carolinan commented on patterns/centered-statement.php
> +<div class="wp-block-group alignwide"><!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.3","fontStyle":"normal","fontWeight":"400"},"spacing":{"padding":{"top":"12rem","botto
Here, we shouldn't duplicate the values that are the defaults, like the font style, font weight, background color, and text color.
We also don't need to duplicate the settings and add them to both the group and the paragraph.

2023-09-02 06:12 UTC, carolinan commented on patterns/centered-statement.php
> +<!-- /wp:group -->
```suggestion
<!-- /wp:group -->

```
Add a blank line.

2023-09-02 06:13 UTC, carolinan commented on patterns/centered-statement.php
> +<div class="wp-block-group alignwide"><!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.3","fontStyle":"normal","fontWeight":"400"},"spacing":{"padding":{"top":"12rem","botto
Instead of hardcoding 12  and 13 rem,  please select a spacing preset.

2023-09-04 07:30 UTC, MaggieCabrera requested changes
Besides the already pointed out issues, this PR needs some linting. Please check the [readme](https://github.com/WordPress/twentytwentyfour#testing) for instructions on how to do so. You will probably need to rebase this PR and run composer run standards:fix to do so. Let us know if you have any issues doing this.

2023-09-05 16:30 UTC, MaggieCabrera commented
I made some changes and switched the text back to Italian (the language was intended to be Italian, we shouldn't translate the patterns), somehow I see my changes in the fork but not on this PR, I'm going to give it some time

2023-09-05 19:59 UTC, MaggieCabrera approved these changes

2023-09-05 19:59 UTC, merged