Created new pattern service-pattern
WordPress/twentytwentyfour pull request #53
Opened 2023-08-24 20:15 UTC by gnanasekaranl

2023-08-24 20:22 UTC, luminuu requested changes

2023-08-24 20:22 UTC, luminuu commented on patterns/services.php
> +<h3>Guiding your business through the project</h3>
Please make all strings translateable, see other patterns how to do it.

2023-08-24 20:22 UTC, luminuu commented on patterns/services.php
> +<p>Experience the fusion of imagination and expertise with Études—the catalyst for architectural transformations that enrich the world around us.</p>
See above

2023-08-24 20:22 UTC, luminuu commented on patterns/services.php
> +<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Learn More</a></div>
See above

2023-09-04 07:40 UTC, MaggieCabrera commented
Closing this since we already merged https://github.com/WordPress/twentytwentyfour/pull/94. Thanks for your contribution!

2023-09-04 07:40 UTC, closed without merging