Newsletter Subscription pattern
WordPress/twentytwentyfour pull request #57
Opened 2023-08-24 20:54 UTC by amedv

Based on Landing Page in Figma template, named it Newsletter Subscription to represent what this template actually doing.

Set to full width but noticed that now all full width block squeezed after publishing (before they looked good), will open separate issue for this.

2023-08-29 12:27 UTC, huzaifaalmesbah requested changes

2023-08-29 12:27 UTC, huzaifaalmesbah commented on patterns/newsletter-subscription.php
> +<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"15rem","bottom":"15rem","right":"10rem","left":"10rem"},"blockGap":"2.5rem"}},"backgroundColor":"custom-brick","layout":{"type":"de
backgroundColor `custom-brick` to `accent-3`

2023-08-29 12:27 UTC, huzaifaalmesbah commented on patterns/newsletter-subscription.php
> +<div class="wp-block-group alignwide has-custom-brick-background-color has-background" style="padding-top:15rem;padding-right:10rem;padding-bottom:15rem;padding-left:10rem"><!-- wp:image {"align":"ce
`has-custom-brick-background-color` to `has-accent-3-background-color`

2023-08-29 12:27 UTC, huzaifaalmesbah commented on patterns/newsletter-subscription.php
> +<figure class="wp-block-image aligncenter size-full"><img src="<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/message_icon.png" alt="" class="wp-image-22"/></figure>
Please replace `get_stylesheet_directory_uri()` with `get_template_directory_uri()` to load images from assets

2023-08-29 12:27 UTC, huzaifaalmesbah commented on patterns/newsletter-subscription.php
> +<!-- /wp:group -->
Add one blank new line after you end code

2023-08-30 17:55 UTC, closed without merging

2023-08-30 17:55 UTC, richtabor commented
Looks like we already have this one in the theme(though the image doesn't seem to be loading, if you want to look into that). 
 
<img width="187" alt="CleanShot 2023-08-30 at 13 54 03" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/dac24010-7fed-4a89-b6bb-7583d2572f74">