Fix button padding in style variations
WordPress/twentytwentyfour pull request #643
Opened 2023-10-13 13:38 UTC by luminuu

As discussed in #569, the size of buttons in the Sandstorm and Fossil style variations should match with all other buttons. Removing extra padding from the style variations.

2023-10-13 13:54 UTC, richtabor requested changes
I don't agree. Buttons can be different sizes in variations. 

> We should have the buttons be the original size like the outline.

The problem is that "outline" variations use core padding styles, not what is defined in the theme.json button styles. So the outline variations are different sizes. 

The problem is not that buttons are different sizes in variations — but that's not something we can fix in the theme (easily). 

I think we need even more variety across variations, and button styles are the easiest way to add that.

2023-10-13 14:02 UTC, richtabor commented
It is possible to force our theme.json values on the outline button, but I think it's probably a bit too much lifting out of the box. Here's a rough draft of what that could look like. Then you'd need to enqueue it with wp_add_inline_style perhaps within the editor and the front end. 

I don't _think_ we should do this — what do you think? 

```
	function twentytwentyfour_outline_button_padding() {

		$padding = \WP_Theme_JSON_Resolver::get_merged_data()->get_raw_data()['styles']['elements']['button']['spacing']['padding'];

		$top    = isset( $padding['top'] ) ? "padding-top: {$padding['top']};" : null;
		$right  = isset( $padding['right'] ) ? "padding-right: {$padding['right']};" : null;
		$bottom = isset( $padding['bottom'] ) ? "padding-bottom: {$padding['bottom']};" : null;
		$left   = isset( $padding['left'] ) ? "padding-left: {$padding['left']};" : null;

		$output = '';

		if ( isset( $padding ) ) {

			$output .= '
				.wp-block-button.is-style-outline > .wp-block-button__link {
					' . esc_attr( $top . $right . $bottom . $left ) . '
				}
			';

		}

		return $output;

	}
```

![CleanShot 2023-10-13 at 10 01 10](https://github.com/WordPress/twentytwentyfour/assets/1813435/c4166837-0de4-491e-9662-ee5141105840)

2023-10-13 14:06 UTC, luminuu commented
I've just done this PR as per request from @beafialho in the issue.

I personally think we should not add custom functionality via PHP to change something that is defined primarily in theme.json - it will just generate too much confusion for the user and fellow theme developers when they want to change the padding but can't.

Either we go with this PR or we don't. As much as I appreciate the input, with just a weekend short of RC1, I want to get things smoothened out as much as possible.

2023-10-13 14:41 UTC, MaggieCabrera commented
So:

- I agree that having different sized buttons between variations is absolutely fine
- I wouldn't add the PHP to fix the size difference with outlined buttons and I'd rather keep said difference if that may be

So I'd rather not go with this one at all. Do we have patterns that have an outlined and a filled button together? I would manually fix those maybe and leave the defaults as they are.

2023-10-13 15:14 UTC, richtabor commented
> So:
> 
> 
> 
> - I agree that having different sized buttons between variations is absolutely fine
> 
> - I wouldn't add the PHP to fix the size difference with outlined buttons and I'd rather keep said difference if that may be
> 
> 
> 
> So I'd rather not go with this one at all. Do we have patterns that have an outlined and a filled button together? I would manually fix those maybe and leave the defaults as they are.

Agreed. I think there's one pattern.

2023-10-16 10:09 UTC, MaggieCabrera commented
Closed in favor of https://github.com/WordPress/twentytwentyfour/pull/646

2023-10-16 10:09 UTC, closed without merging