Hero pattern
WordPress/twentytwentyfour pull request #67
Opened 2023-08-25 08:23 UTC by maneshtimilsina

2023-08-25 08:35 UTC, kafleg commented
Looks good to me. But, I see this pattern is already in the home.php pattern. But I think creating a separate pattern for each section is good.

2023-08-25 08:35 UTC, kafleg approved these changes

2023-08-29 00:05 UTC, MaggieCabrera requested changes
Same comment as in your previous PR, let's move the markup from the original template without modifying any of the design elements (just adding translation and image urls) and replace with the pattern block in the original template

2023-08-29 05:50 UTC, maneshtimilsina commented
@MaggieCabrera changes are done and updated as per your instructions. Please verify it and let me know if there is anything left to do.

2023-08-30 11:17 UTC, maneshtimilsina commented
@MaggieCabrera I haven't replaced the content of `home.php` to avoid merge conflict. I think it will be better to replace the codes of `home.php` with patterns once all patterns are approved and merged to the trunk.

2023-08-30 17:58 UTC, richtabor commented
>  I think it will be better to replace the codes of home.php with patterns once all patterns are approved and merged to the trunk.

Agreed. We'll probably consolidate once the individual patterns are cleaned up.

2023-08-30 17:58 UTC, richtabor commented on patterns/hero.php
> +<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"6vh","bottom":"6vh"}}},"layout":{"type":"constrained"}} -->
Instead of arbitrary values, let's use the spacing presets for paddings throughout.

2023-08-30 17:59 UTC, richtabor requested changes, later dismissed

2023-08-30 17:59 UTC, richtabor commented on patterns/hero.php
> +<p class="has-text-align-center has-small-font-size" style="padding-right:0;padding-left:0"><?php echo esc_html_x( 'Études is a pioneering firm that seamlessly merges creativity and functionality to
Not sure if removing the padding is necessary here.

2023-08-30 17:59 UTC, richtabor commented on patterns/hero.php
> +<!-- wp:image {"align":"wide","id":369,"sizeSlug":"full","linkDestination":"none"} -->
We should remove the ID attribute and class for images.

2023-08-30 18:00 UTC, richtabor commented
This is what I'm seeing? 

<img width="1461" alt="CleanShot 2023-08-30 at 14 00 38" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/8a05366b-a706-422f-a859-bd9671ec9a2e">

2023-08-30 18:01 UTC, richtabor commented on patterns/hero.php
> +<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"6vh","bottom":"6vh"}}},"layout":{"type":"constrained"}} -->
Let's also make it fullwidth.

2023-08-30 18:02 UTC, richtabor commented
Let's try using spacer blocks (with preset, not pixels) instead of block gap for these here. Its easier for people to grab the space and adjust, rather than finding the block gap control: 

<img width="699" alt="CleanShot 2023-08-30 at 14 01 25" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/ffb270d2-c1ab-4a33-b101-cf79672be410">

2023-09-04 08:01 UTC, MaggieCabrera commented
@maneshtimilsina are you working on the changes to this PR?

2023-09-04 08:03 UTC, maneshtimilsina commented
@MaggieCabrera Yes, I will push my changes until Tuesday.

2023-09-04 11:20 UTC, maneshtimilsina commented
@MaggieCabrera I have made the changes according to the suggestions of @richtabor and pushed the changes. @richtabor Can you please check it and let me know if you have any suggestions?

2023-09-04 16:24 UTC, MaggieCabrera approved these changes
This is looking great, thanks!

2023-09-04 16:24 UTC, MaggieCabrera commented on patterns/hero.php
> +<div class="wp-block-button"><a class="wp-block-button__link wp-element-button"><?php echo esc_html_x( 'Learn More', 'Button of the hero section', 'twentytwentyfour' ); ?></a></div>
```suggestion
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button"><?php echo esc_html_x( 'Learn More', 'Button\'s label of the hero section', 'twentytwentyfour' ); ?></a></div>
```

2023-09-04 16:26 UTC, MaggieCabrera approved these changes

2023-09-04 16:27 UTC, merged