Create Features with Images Patterns
WordPress/twentytwentyfour pull request #96
Opened 2023-08-26 21:12 UTC by huzaifaalmesbah

Create Features with Images Patterns

2023-08-29 08:04 UTC, maneshtimilsina commented
@huzaifaalmesbah You are using `get_stylesheet_directory_uri()` to load images from assets. It will not work if we use a child theme. It will be better to replace it with `get_template_directory_uri()` as discussed here https://github.com/WordPress/twentytwentyfour/issues/101

2023-08-29 08:11 UTC, maneshtimilsina requested changes
Please replace `get_stylesheet_directory_uri()` with `get_template_directory_uri()` to load images from assets so that the pattern will work with the child theme too.

2023-08-29 08:18 UTC, huzaifaalmesbah commented
> Please replace `get_stylesheet_directory_uri()` with `get_template_directory_uri()` to load images from assets so that the pattern will work with the child theme too.

OK. thanks for the suggestion

2023-08-29 15:33 UTC, maneshtimilsina commented
@huzaifaalmesbah I think `✳︎` needs to be translatable.

2023-08-29 15:34 UTC, maneshtimilsina commented on patterns/features-with-images.php
> +<p class="has-text-align-center has-custom-borders-color has-text-color has-link-color has-large-font-size" style="padding-right:0;padding-left:0">✳︎</p>
This icon/character `✳︎` needs to be translatable.

2023-08-29 15:55 UTC, maneshtimilsina approved these changes
Looks good to me.

2023-09-02 05:00 UTC, carolinan commented on patterns/features-with-images.php
> +<div class="wp-block-group"><!-- wp:paragraph {"align":"left","style":{"layout":{"selfStretch":"fit","flexSize":null},"spacing":{"padding":{"right":"0","left":"0"}},"elements":{"link":{"color":{"text
Why does the padding need to be set to 0 here?

2023-09-02 05:02 UTC, carolinan commented on patterns/features-with-images.php
> +<h3 class="wp-block-heading has-large-font-size"><?php echo esc_html__( 'Études Architect App', 'twentytwentyfour' ); ?></h3>
H3 uses the large font size by default, so this size should be removed from the pattern.

2023-09-04 08:36 UTC, huzaifaalmesbah commented on patterns/features-with-images.php
> +<h3 class="wp-block-heading has-large-font-size"><?php echo esc_html__( 'Études Architect App', 'twentytwentyfour' ); ?></h3>
Thanks for the review and your feedback. I will asap update PR.

2023-09-04 08:54 UTC, MaggieCabrera commented
This is a duplicate of https://github.com/WordPress/twentytwentyfour/pull/69

2023-09-06 11:04 UTC, MaggieCabrera commented
Closing in favor of #69

2023-09-06 11:04 UTC, closed without merging